# Name of the snippet:
TARGET_NAME = program

# Specify all source files:
SOURCES = main.c
SOURCES += rocks.c

# Specify all include paths:
INCLUDES = -I.
# INCLUDES += -I...

# Specify defines:
DEFINES =
#DEFINES += ...

include ../global.mk
